# .travis.yml
language: node_js # 前端工程所以是JavaScript，编译环境是node_js
git:
  depth: 1
node_js:
  - 'lts/*'
branchs:
  only:
    - master # 指定只有检测到master分支有变动时才执行git 任务
before_install:
  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm i
script:
  - npm run test
  - npm run build:doc
  - scp -r -o StrictHostKeyChecking=no build/ng-hertz-doc travis@39.107.82.42:/www/wwwroot/ssr/panel/public
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi
  # travis 默认当有 新 pr 提交时会触发任务，当为 pr 触发时不去服务器构建，因为下面执行的脚本里只构建 master 分支
  # - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then who && ssh travis@39.107.82.42 -o StrictHostKeyChecking=no 'sh scripts/travis-deploy.sh'; fi
notifications:
  email:
    recipients:
      - ieloul@foxmail.com
    on_failure: always
