# .travis.yml
language: node_js #前端工程所以是JavaScript，编译环境是node_js
node_js:
  - '10' #指定node版本
branchs:
  only:
    - master #指定只有检测到master分支有变动时才执行git 任务
before_install:
  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
install:
  - npm i
  - npm run build:doc
notifications:
  email:
    recipients:
      - ieloul@foxmail.com
    on_success: always
    on_failure: always
after_success:
  - ssh travis@39.107.82.42 -o StrictHostKeyChecking=no "cp build/ng-hertz-doc /www/wwwroot/ssr/panel/public/ng-hertz-doc"
